package javapackages;

public class CallMe {

//	This constructor is executed while an object for this class is 
//	created
	CallMe(){
		System.out.println("This is autogenerated message from CallMe");
	}
	
	CallMe(String code){
		System.out.println("This is autogenerated message from "
				+ "argument constructor of CallMe");
		System.out.println("Code is:"+code);
	}
}
